import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Next js JWT With Middleware</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">Index</div>
    </div>
  )
}
